CPPFLAGS = -c -std=c++11
SFMLFLAGS = -lsfml-graphics -lsfml-window -lsfml-system
UTFLAGS = -lunittest++
CPPUFLAGS= -lcppunit

OBJFILES = tests.o cotw.tests.o game.o map.o player.o tile.o texture_manager.o 

tests: $(OBJFILES)
	g++ $(OBJFILES) -o $@ $(SFMLFLAGS) $(CPPUFLAGS)

tests.o: tests.cpp 
	$(CC) $(CPPFLAGS) tests.cpp 

cotw.tests.o: cotw.tests.cpp 
	$(CC) $(CPPFLAGS) cotw.tests.cpp 

game.o: game.cpp 
	$(CC) $(CPPFLAGS) game.cpp 

map.o: map.cpp 
	$(CC) $(CPPFLAGS) map.cpp 

player.o: player.cpp 
	$(CC) $(CPPFLAGS) player.cpp 

tile.o: tile.cpp 
	$(CC) $(CPPFLAGS) tile.cpp 

texture_manager.o: texture_manager.cpp 
	$(CC) $(CPPFLAGS) texture_manager.cpp 

clean:
	rm *.o tests 
